#!/usr/bin/env bash

FLOCK="$XDG_RUNTIME_DIR/fuzzel-$WAYLAND_DISPLAY.lock"

if [ "$1" == "wipe" ]; then
    if [ $(~/.local/scripts/cliphist list | wc -l) -eq 0 ]; then
        exit 0
    fi    
    ~/.local/scripts/cliphist wipe
    if [[ -f $FLOCK ]]; then    
        killall fuzzel
        rm $FLOCK
    fi
    notify-send 'Clipboard' 'Wiped the clipboard clean!'
    exit 0
fi

if pgrep -f fuzzel.*clip-menu >/dev/null; then    
    exit 0
fi

if [ -f $FLOCK ]; then    
    killall fuzzel
    rm $FLOCK
fi

# 1. Get the list and selection
# We pipe the selected line to awk to grab just the first field (the ID)
RESULT=$(~/.local/scripts/cliphist list | fuzzel --namespace clip-menu \
    --dmenu \
    --prompt="󱘝 : " \
    --placeholder="検索履歴..." \
    --width=50 \
    --lines=10)

# 2. Check if the user canceled
if [ -z "$RESULT" ]; then
    exit 0
fi

# 3. Extract the ID and decode it
# 'awk {print $1}' grabs the ID (e.g., "0", "1", "2")
echo "$RESULT" | awk '{print $1}' | cliphist decode | wl-copy
rm $SLOCK

# 4. Optional: Send a tiny notification that it worked
notify-send "Clipboard" "Copied to clipboard!" -i clipboard
