#!/usr/bin/env bash

case $1 in
    vol)   pavucontrol ;;
    blue)  blueman-manager ;;
    net)   nm-connection-editor ;;
    dash)  kitty --class dashboard-popup -e btop ;;
    *)     echo "Usage: control-center {vol|blue|net|dash}" ;;
esac
