#!/usr/bin/env bash

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"
NAME="$DIR/screenshot_$(date +%Y%m%d_%H%M%S).png"

# Check if the "full" argument was passed
if [ "$1" == "full" ]; then
    grim "$NAME"
    paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga &
    wl-copy < "$NAME"
    notify-send "スクリーンショット" "Full screen saved" -i "$NAME"
else
    AREA=$(slurp 2>/dev/null)
    [ -z "$AREA" ] && exit 0
    grim -g "$AREA" - | tee "$NAME" | wl-copy
    paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga &
    notify-send "スクリーンショット" "Area captured" -i "$NAME"
fi
