#!/usr/bin/env bash

# Setup
DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"
# Sound file (standard location on most distros)
SOUND="/usr/share/sounds/freedesktop/stereo/camera-shutter.oga"

# Function to play shutter sound in the background
play_sound() {
    if [ -f "$SOUND" ]; then
        pw-play "$SOUND" &
    fi
}

# Capture Logic
if [ "$1" == "full" ]; then
    play_sound
    # Capture full screen and pipe to swappy
    grim - | swappy -f -
else
    AREA=$(slurp -b "#24273aaa" -c "#8aadf4" -s "#8aadf422" -w 2)
    [ -z "$AREA" ] && exit 0
    
    play_sound
    # Capture area and pipe to swappy
    grim -g "$AREA" - | swappy -f -
fi
