#!/bin/bash

sudo dnf install @hardware-support

sudo dnf install \
    blueman \
    brightnessctl \
    btop \
    firefox \
    flatpak \
    gnome-themes-extra \
    google-noto-sans-cjk-vf-fonts \
    kitty \
    nautilus \
    neovim \
    niri \
    nm-connection-editor \
    nu \
    pavucontrol \
    plymouth-system-theme \
    stow \
    swaybg \
    swayidle \
    swaync \
    tar \
    tuigreet \
    xdg-user-dirs \
    zip

#sudo dnf remove alacritty
echo "Installing plymounth theme, may take a while..."
sudo plymouth-set-default-theme -R "bgrt"

sudo cp ./.no-stow/config.toml /etc/greetd/
sudo systemctl set-default graphical.target
sudo systemctl enable greetd

sudo flatpak remote-add --if-not-exists flathub \
    https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak install flathub io.github.kolunmi.Bazaar

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
xdg-user-dirs-update

stow btop fuzzel kitty niri swaylock wallpapers fonts gtk-4.0 nushell starship swaync waybar wbin

sudo curl -sS https://starship.rs/install.sh | sh
