#!/bin/bash

sudo dnf install @hardware-support

sudo dnf install \
    blueman \
    brightnessctl \
    firefox \
    flatpak \
    fzf \
    git \
    google-noto-sans-cjk-vf-fonts \
    kitty \
    nautilus \
    neovim \
    niri \
    nm-connection-editor \
    nu \
    pavucontrol \
    plymouth-system-theme \
    stow \
    swaybg \
    swayidle \
    swaync \
    tar \
    tuigreet \
    zip

sudo curl -sS https://starship.rs/install.sh | sh
mkdir ($nu.data-dir | path join "vendor/autoload")
starship init nu | save -f ($nu.data-dir | path join "vendor/autoload/starship.nu")

sudo dnf remove alacritty

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

sudo plymouth-set-default-theme -R "bgrt"

sudo flatpak remote-add --if-not-exists flathub \
    https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak install flathub io.github.kolunmi.Bazaar
